# Ring that bell

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - displayTargetName: ubuntu
            os: ubuntu-latest
          - displayTargetName: windows
            os: windows-latest
          - displayTargetName: mac
            os: macos-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # we don't have to install Bazelisk because it comes with the modern Github runners
      # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-software

      - name: Build
        run: |
          bazel --version
          bazel build //...

      - name: Test
        run: |
          bazel test //...
