# Ring that bell

name: Release

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      tag:
        description: 'Release version tag (e.g. 1.0.0)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        run: |
          bazel build //...

      - name: Test
        run: |
          bazel test //...

      - name: Create Release
        uses: ncipollo/release-action@v1.8.6
        with:
          allowUpdates: false
          artifactErrorsFailBuild: true
          artifacts: "bazel-bin/sdk/bazel-java-sdk/libbazel-java-sdk.jar"
          omitNameDuringUpdate: true
          tag: ${{ github.event.inputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
